worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # CDN Keepalive Tuning
    keepalive_timeout 120s;
    keepalive_requests 1000;

    upstream xray_ws {
        server 127.0.0.1:8080;
        keepalive 64;
    }

    server {
        listen 80;
        server_name _;

        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 🚀 [အဓိကပြင်ဆင်ချက်] ဝင်လာသမျှ Traffic အားလုံးကို WebSocket (Xray) ထဲ တိုက်ရိုက်မောင်းထည့်မည်
        location / {
            proxy_redirect off;
            proxy_pass http://xray_ws;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            # Request က ဝင်လာတဲ့ Host အတိုင်း Xray Core ဆီ လက်ဆင့်ကမ်းရန်
            proxy_set_header Host $http_host; 
        }
    }
}
